### ISSUE TITLE
How can I try this out?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/atom-fstar#1]
Naive question: How can I try this out?
I've tried installing this with `apm`:

```
[FStarIDE]$ apm install
Installing modules ✓
[FStarIDE]$
```

But then nothing changed after restarting the editor: no syntax highlighting for `.fst` files and `language-fstar` doesn't appear in the list of installed packages. Is this supposed to do anything at this point? :)

**Comment by strub** [comment]
What I did is to go to `.atom/packages` and link FStarIDE. Now, apm may have copied some files in that directory too.

Currently, I only set up an empty shell package (it only highlights some keywords).

**Comment by catalin-hritcu** [comment]
A symlink indeed worked. Apparently `atm install` did nothing (the `packages` folder at least was empty).
![screenshot from 2015-04-18 16-09-46](https://cloud.githubusercontent.com/assets/5850655/7215742/f46d0af6-e5e4-11e4-9f08-b8089c677222.png)

**Comment by strub** [comment]
Ok. It may be a problem with the package.json file. I'll investigate this.

**Comment by strub** [comment]
What a beautiful integer overflow in your screenshot :)

**Comment by nikswamy** [comment]
We have a readme now.
