### ISSUE TITLE
Unknown key editor in grammar

### ISSUE THREAD

**Issue by pchaigno** [FStarLang/atom-fstar#6]
Hello there :wave: !

I'm working on adding F* support in GitHub (language entry and syntax highlighting) over at [github/linguist](https://github.com/github/linguist).

We use a compiler to process grammars before linking them to Linguist. That compiler throws a warning for [the `editor` key](https://github.com/FStarLang/atom-fstar/blob/30fb027cf8725898dcabf6d4aa2c513418bc2a52/grammars/fstar.cson#L7) in `fstar.cson` because it doesn't recognize it. Is that a standard Atom grammar entry? Do you know where I could find its documentation?

**Comment by beurdouche** [comment]
Hi Paul @pchaigno ! 👋
Thanks for looking into this, it would be very helpful for us to have support in Github, especially now that we ship lots of code :)
We'll try to help you as much as possible on this...

**Comment by ad-l** [comment]
The atom grammar is severely outdated... but we'll probably find some time to refresh it quickly, if that's what it takes to get linguist support

**Comment by pchaigno** [comment]
@ad-l I think just removing the `editor` key in the grammar should be enough for Linguist support. I don't think it's needed in the grammar anyway as it's already defined in `scoped-properties/language-fstar.cson`. I haven't had time to test it though.

**Comment by beurdouche** [comment]
@pchaigno How easy for you is it to update the grammar after the fact ?
I am thinking I could just do the easy fix now (removing the `editor` key), so that you can make progress and leave us a few weeks to properly rewrite the grammar for an update...
What would you prefer ?

**Comment by beurdouche** [comment]
CC @A-Manning

**Comment by pchaigno** [comment]
@beurdouche We update the grammars automatically with each new release of Linguist so there's really no burden on our side :+1:

**Comment by beurdouche** [comment]
Ok, let me remove that field now then : )

**Comment by beurdouche** [comment]
@pchaigno You should be good to go now... 👍 Let me know how it goes ; )

**Comment by pchaigno** [comment]
Great! I'll update the pull request when I get a moment.

Thanks!
